language: node_js

node_js: "8.9.4"

dist: trusty
sudo: required
services:
  - docker

git:
  depth: 1

os: osx

cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew

before_install:
    - brew update
    - brew install emscripten || ./.emscripten-install.sh || true

install:
  - npm install

script:
  - emcc --version
  - npm run build
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh_token
  local_dir: dist
  target-branch: dist
