language: node_js

node_js: "8.9.4"

dist: trusty
sudo: required
services:
  - docker

git:
  depth: 1

os: osx

cache:
  directories:
    - node_modules

before_install:
    - brew update
    - brew install qt5 cmake
    - brew link --force qt

install:
  - npm install
  - ./.emscripten-install.sh

build:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh_token
  local_dir: dist
  target-branch: dist
